# Generated by Django 4.1.1 on 2022-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255, unique=True)),
                ('plik', models.FileField(upload_to='dokumenty/')),
                ('data_d', models.DateTimeField(auto_now_add=True, verbose_name='dodano')),
            ],
            options={
                'verbose_name_plural': 'dokumenty',
            },
        ),
        migrations.AlterModelOptions(
            name='absolwent',
            options={'verbose_name_plural': 'absolwenci'},
        ),
        migrations.AlterModelOptions(
            name='klasa',
            options={'ordering': ['rok_naboru'], 'verbose_name_plural': 'klasy'},
        ),
    ]
