# Generated by Django 4.1.1 on 2022-11-21 08:22

from django.db import migrations, models
import osoby.models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_dokument_alter_absolwent_options_alter_klasa_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='typ',
            field=models.CharField(choices=[('K', 'Lista klas'), ('U', 'Lista uczniów')], default='K', max_length=1),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='plik',
            field=models.FileField(upload_to='dokumenty/', validators=[osoby.models.rozmiar_pliku]),
        ),
    ]
